# Generated by Django 5.0 on 2023-12-11 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AshesiEmployee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('ashesi_email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('momo_network', models.CharField(max_length=50)),
                ('momo_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'ashesi_employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('trip_date', models.DateField()),
            ],
            options={
                'db_table': 'trip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SemesterSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('time_period', models.CharField(max_length=7)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'semester_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SemesterScheduleStop',
            fields=[
                ('sem_sched_stop_id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('arrival_time', models.TimeField()),
            ],
            options={
                'db_table': 'semester_schedule_stop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('stop_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=150, unique=True)),
                ('cost', models.FloatField()),
            ],
            options={
                'db_table': 'stops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField()),
                ('ticket_price', models.FloatField()),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('license_plate', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(blank=True, max_length=15, null=True)),
                ('capacity', models.IntegerField()),
                ('descriptive_name', models.CharField(max_length=100)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('permit_issuer', models.CharField(blank=True, max_length=100, null=True)),
                ('permit_issue_date', models.DateField(blank=True, null=True)),
                ('permit_expiry_date', models.DateField(blank=True, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('maintenance_cycle_days', models.IntegerField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehicles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('drivers_license_number', models.CharField(max_length=20)),
                ('license_expiry_date', models.DateField()),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeTrip',
            fields=[
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Logistics_ticket_API.trip')),
            ],
            options={
                'db_table': 'employee_trip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateTrip',
            fields=[
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Logistics_ticket_API.trip')),
                ('trip_notes', models.CharField(blank=True, max_length=600, null=True)),
                ('client_list', models.CharField(blank=True, max_length=600, null=True)),
            ],
            options={
                'db_table': 'private_trip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StaffShuttleTrip',
            fields=[
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Logistics_ticket_API.trip')),
            ],
            options={
                'db_table': 'staff_shuttle_trip',
                'managed': False,
            },
        ),
    ]
