# Generated by Django 4.2.7 on 2023-11-26 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AshesiEmployee',
            fields=[
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('ashesi_email', models.CharField(max_length=100)),
                ('account_password', models.CharField(max_length=250)),
                ('momo_network', models.JSONField()),
                ('momo_number', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ashesi_employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('drivers_license_number', models.CharField(max_length=20)),
                ('license_expiry_date', models.DateField()),
            ],
            options={
                'db_table': 'driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SemesterSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.JSONField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
            ],
            options={
                'db_table': 'semester_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('stop_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=150, unique=True)),
                ('cost', models.FloatField()),
            ],
            options={
                'db_table': 'stops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField()),
                ('ticket_price', models.FloatField()),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('trip_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'trip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('license_plate', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('vehicle_type', models.JSONField()),
                ('capacity', models.IntegerField()),
                ('descriptive_name', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('permit_issuer', models.CharField(max_length=100)),
                ('permit_issue_date', models.DateField()),
                ('permit_expiriy_date', models.DateField()),
            ],
            options={
                'db_table': 'vehicles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeTrip',
            fields=[
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Logistics_ticket_API.trip')),
            ],
            options={
                'db_table': 'employee_trip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateTrip',
            fields=[
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Logistics_ticket_API.trip')),
                ('trip_notes', models.CharField(blank=True, max_length=600, null=True)),
                ('client_list', models.CharField(blank=True, max_length=600, null=True)),
            ],
            options={
                'db_table': 'private_trip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SemesterScheduleStop',
            fields=[
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Logistics_ticket_API.semesterschedule')),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('arrival_time', models.TimeField()),
            ],
            options={
                'db_table': 'semester_schedule_stop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StaffShuttleTrip',
            fields=[
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Logistics_ticket_API.trip')),
            ],
            options={
                'db_table': 'staff_shuttle_trip',
                'managed': False,
            },
        ),
    ]
